# Generated by Django 3.2.19 on 2026-05-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20260522_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['name'], name='movies_movi_name_98114c_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['language'], name='movies_movi_languag_42452e_idx'),
        ),
    ]
