# Generated by Django 5.2.14 on 2026-05-26 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_booking_movies_book_booked__a7ab7e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_seats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['is_booked'], name='movies_seat_is_book_ae17f5_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['reserved_at'], name='movies_seat_reserve_bdae76_idx'),
        ),
    ]
